# Creating models
- nn.Module
- Data Types
- nn.Sequential

In [0]:
!pip3 install torch torchvision

In [0]:
import numpy as np
import pandas as pd
import torch, torchvision
torch.__version__

'0.4.1'

## 1. nn.Module
- When using Pytorch, machine learning (ML) models are constructed using ```torch.nn```, especially ```torch.nn.Module```.
  - Create a subclass of ```nn.Module```, and a model instance from that class
  - Documentation: [```torch.nn```](https://pytorch.org/docs/stable/nn.html)
 
- When implementing a ML model using ```torch.nn```, at least two functions should be specified in detail
  - ```__init__()```: define structure of the model and its parameters
  - ```forward```: define operation between layers (e.g., convolution, pooling, activation, ...)
  
 ```python
class MyModel(nn.Module):
    def __init__(self):
      super(MyModel, self).__init__()
      define model structure
    def forward(self, x):
      define operation
```

In [0]:
import torch.nn as nn

# creating a simplest linear regression model
class linear(nn.Module):
  def __init__(self):
    super(linear, self).__init__()
    self.dense = nn.Linear(5, 1)    # input features = 5, output features = 1
    
  def forward(self, x):
    x = self.dense(x)
    return x  

In [0]:
model = linear()
model

linear(
  (dense): Linear(in_features=5, out_features=1, bias=True)
)

In [0]:
# model parameters can be viewed with parameters()
# usually, parameters are passed onto optimizers (e.g., Adam) to perform gradient descent
for p in model.parameters():
  print(p)

Parameter containing:
tensor([[ 0.0432, -0.0955,  0.1572,  0.1421, -0.1961]], requires_grad=True)
Parameter containing:
tensor([0.1085], requires_grad=True)


In [0]:
# c.f. if you want to save parameters in a list...
nn.ParameterList(model.parameters())

ParameterList(
    (0): Parameter containing: [torch.cuda.FloatTensor of size 1x5 (GPU 0)]
    (1): Parameter containing: [torch.cuda.FloatTensor of size 1 (GPU 0)]
)

In [0]:
# state_dict() returns OrderedDict with layer names mapped to weights
model.state_dict()

In [0]:
# output from a single data instance can be generated
x = torch.randn(5, dtype = torch.float)   # generate a single data instance
print(x)
print(model(x))    # output result

tensor([-0.1225, -2.0576,  0.9150, -1.9567, -0.8272])


In [0]:
# output from multiple data instances can be generated
x = torch.randn(3, 5, dtype = torch.float)    # generate 3 random data instance
print(x)
print(model(x))     # output result

tensor([[-0.4397,  1.2041, -0.6803, -0.6452, -1.2140],
        [ 0.0292, -0.9331,  0.4583,  0.1276, -0.9395],
        [-0.0179, -0.5324,  0.3720,  0.5575, -1.5623]])
tensor([[0.0139],
        [0.4732],
        [0.6025]], grad_fn=<ThAddmmBackward>)


## 2. Data Types of Models
- In Pytorch, models have data types and they should be aligned with input data types
- Also, a model can be changed into GPU model. In this case, data type of input should be GPU-compatible as well.
```python
model.to(device)```

In [0]:
model = model.double()    # model has data type of double
print(x.dtype)            # x has data type of float
print(model(x))           # error

In [0]:
model = model.float()     # now change model to float 
print(x.dtype)            # x has data type of float
print(model(x))           # no error

torch.float32
tensor([[0.0139],
        [0.4732],
        [0.6025]], grad_fn=<ThAddmmBackward>)


In [0]:
device = torch.device("cuda")
model = model.to(device)
x = x.to(device)
print(model(x))

tensor([[0.0139],
        [0.4732],
        [0.6025]], device='cuda:0', grad_fn=<ThAddmmBackward>)


## 3. nn.Sequential
- Sequential container in which modules can be added **in order**
  - Also, ```OrderedDict``` can be used as an input

In [0]:
# create a simple multi-layer perceptron
model = nn.Sequential(
          nn.Linear(5, 5),
          nn.ReLU(),
          nn.Linear(5, 1),
          nn.Sigmoid()
          )

In [0]:
x = torch.randn(5, dtype = torch.float)
model(x)

tensor([0.6740], grad_fn=<SigmoidBackward>)

In [0]:
# create MLP using ordereddict - same result as above
from collections import OrderedDict

model = nn.Sequential(OrderedDict([
    ("dense1", nn.Linear(5,5)),
    ("relu1", nn.ReLU()),
    ("dense2", nn.Linear(5,1)),
    ("relu2", nn.ReLU())
]))