# Building Blocks of Models
- Convolution & Pooling
- Padding

In [0]:
!pip3 install torch torchvision

In [0]:
import numpy as np
import pandas as pd
import torch, torchvision
torch.__version__

'0.4.1'

In [0]:
import torch.nn as nn

## 1. Convolution & Pooling 
Convolution and pooling are fundamental operations for building CNN models. There are a number of parameters and if their definitions are not clear, it could lead to great confusion.
- Parameters for convolution (pooling) layers
  - **stride:** how many "steps" that the filter makes for each advance
  - **kernel size**: how large is the kernel (filter) is
  - **number of filters (channels):** designates the "depth" of the data. Most image inputs have three filters (RGB)
  - **padding:** how to pad the input sample with zero in the border
- How to calculate output size of convolution/pooling operation
  <br> 
*(W - F + 2P)/S + 1* <br>
  - *W*: input size
  - *F*: kernel size
  - *P*: padding 
  - *S*: stride
  
![alt text](https://user-images.githubusercontent.com/22738317/34081046-c3a97518-e347-11e7-98fe-929f602ee857.png)

### 1. Convolution & Pooling 1D

- ```torch.nn.Conv1d()```: 1D convolution
  - Input: (N, Fi, Li): basically, each input is ```Fi``` vectors of length ```Li```
    - N: batch size
    - Fi: number of input filters (or channels)
    - Li: length of input sequence
  - Output: (N, Fo, Lo): each output is ```Fo``` vectors of length ```Lo```
    - N: batch size
    - Fo: number of output filters (or channels)
    - Lo: length of output sequence

In [0]:
# case 1 - kernel size = 1
conv1d = nn.Conv1d(16, 32, kernel_size = 1)

x = torch.ones(128, 16, 10)   # input: batch_size = 128, num_filters = 16, seq_length = 10
print(conv1d(x).size())       # input and output size are equal when kernel_size = 1 (assuming no padding)

torch.Size([128, 32, 10])


In [0]:
# case 2 - kernel size = 2, stride = 1
conv1d = nn.Conv1d(16, 32, kernel_size = 2, padding = 2)

x = torch.ones(128, 16, 10)   # input: batch_size = 128, num_filters = 16, seq_length = 10
print(conv1d(x).size())

torch.Size([128, 32, 13])


In [0]:
# case 2 - kernel size = 2, stride = 2
conv1d = nn.Conv1d(16, 64, kernel_size = 2, stride = 2, padding = 2)

x = torch.ones(128, 16, 10)   # input: batch_size = 128, num_filters = 16, seq_length = 10
print(conv1d(x).size())

torch.Size([128, 64, 7])


### Convolution & Pooling 2D
- ```torch.nn.Conv2d()```:  2D convolution
  - Largely siimilar to 1D-convolution, but input and outputs are 2-dimensional, rather than 1-dimensional
- Image data in Pytorch
  - ```Conv2d()``` is the basic building block of modern CNNs to process image, such as GoogleNet or ResNet
  - In Pytorch, images usually have shape of **\[depth, height, width\]**
    - depth corresponds to the number of filters (kernels)
    - width and height represent the size of an image. When the image is square (e.g., in CIFAR10), width = height
  
  ![alt text](http://cs231n.github.io/assets/cnn/cnn.jpeg)

In [0]:
# case 1 - kernel size = 1
conv2d = nn.Conv2d(16, 32, kernel_size = 1)  # if kernel size is integer, width and height are equal (i.e., square kernel) 

x = torch.ones(128, 16, 10, 10)   # input: batch_size = 128, num_filters = 16, height = 10, width = 10
print(conv2d(x).size())       # input and output size are equal when kernel_size = 1 (assuming no padding)

conv2d = nn.Conv2d(16, 32, kernel_size = (1, 1))  # same as kernel size = 1

x = torch.ones(128, 16, 10, 10)   # input: batch_size = 128, num_filters = 16, height = 10, width = 10
print(conv2d(x).size())       # input and output size are equal when kernel_size = 1 (assuming no padding)

torch.Size([128, 32, 10, 10])
torch.Size([128, 32, 10, 10])


In [0]:
# case 2 - kernel size = 2
conv2d = nn.Conv2d(16, 32, kernel_size = 2, padding = 1)  # if kernel size is integer, width and height are equal (i.e., square kernel) 

x = torch.ones(128, 16, 10, 10)   # input: batch_size = 128, num_filters = 16, height = 10, width = 10
print(conv2d(x).size())       

torch.Size([128, 32, 11, 11])


In [0]:
# case 3 - differing kernel size
conv2d = nn.Conv2d(16, 32, kernel_size = (2, 1))  # if kernel size is integer, width and height are equal (i.e., square kernel) 

x = torch.ones(128, 16, 10, 10)   # input: batch_size = 128, num_filters = 16, height = 10, width = 10
print(conv2d(x).size())     # non-square output

torch.Size([128, 32, 9, 10])


In [0]:
# case 4 - kernel size = 3
conv2d = nn.Conv2d(16, 32, kernel_size = (3, 3), padding = 1)  # if kernel size is integer, width and height are equal (i.e., square kernel) 

x = torch.ones(128, 16, 10, 10)   # input: batch_size = 128, num_filters = 16, height = 10, width = 10
print(conv2d(x).size())     # input and output size are equal

torch.Size([128, 32, 10, 10])


In [0]:
# case 4 - kernel size = 3, stride = 2
conv2d = nn.Conv2d(16, 32, kernel_size = (3, 3), stride = 2)  # if kernel size is integer, width and height are equal (i.e., square kernel) 

x = torch.ones(128, 16, 10, 10)   # input: batch_size = 128, num_filters = 16, height = 10, width = 10
print(conv2d(x).size())     # input and output size are equal

torch.Size([128, 32, 4, 4])


## 2. Padding
- Zero padding can be applied in convolution/pooling as we have seen above. But custom padding can be applied as well
  - ```nn.ConstandPad1d(padding, value)```: apply constant padding on 1D data
    - ```padding```: the shape of padding (if tuple, (```padingLeft```, ```padingRight```))
    - ```value```: the value of padding
  - ```nn.ConstantPad2d(padding, value)```: apply constant padding on 2D data
    - ```padding```: the shape of padding (if tuple, (```padingLeft```, ```padingRight```, ```paddingTop```, ```padingBottom```))
    - ```value```: the value of padding
  - ```nn.ZeroPad2d(padding)```: apply zero padding on 2D data 
    - ```padding```: the shape of padding (if tuple, (```padingLeft```, ```padingRight```, ```paddingTop```, ```padingBottom```))

In [0]:
p = nn.ConstantPad1d(1, 0.75)  # 1d padding with constant 0.75
x = torch.ones(1, 1, 3)
print(p(x))

tensor([[[0.7500, 1.0000, 1.0000, 1.0000, 0.7500]]])


In [0]:
p = nn.ConstantPad2d((2, 2, 0, 0), -1)  # 2d padding with -1 (on right and left)
x = torch.ones(1, 1, 3, 3)
print(p(x))

tensor([[[[-1., -1.,  1.,  1.,  1., -1., -1.],
          [-1., -1.,  1.,  1.,  1., -1., -1.],
          [-1., -1.,  1.,  1.,  1., -1., -1.]]]])


In [0]:
p = nn.ZeroPad2d((1,0,0,0))  # apply zero padding only on the left of first column
x = torch.ones(1, 1, 3, 3)
print(p(x))

tensor([[[[0., 1., 1., 1.],
          [0., 1., 1., 1.],
          [0., 1., 1., 1.]]]])
