# Pytorch Tensors
- Tensors
- Creating Tensors
- Tensor Data Types
- Size (shape) of Tensors

In [1]:
!pip3 install torch torchvision

    100% |████████████████████████████████| 519.5MB 29kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x586b2000 @  0x7f0833a5f1c4 0x46d6a4 0x5fcbcc 0x4c494d 0x54f3c4 0x553aaf 0x54e4c8 0x54f4f6 0x553aaf 0x54efc1 0x54f24d 0x553aaf 0x54efc1 0x54f24d 0x553aaf 0x54efc1 0x54f24d 0x551ee0 0x54e4c8 0x54f4f6 0x553aaf 0x54efc1 0x54f24d 0x551ee0 0x54efc1 0x54f24d 0x551ee0 0x54e4c8 0x54f4f6 0x553aaf 0x54e4c8
    100% |████████████████████████████████| 61kB 21.9MB/s 
    100% |████████████████████████████████| 2.0MB 4.9MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0


In [2]:
import numpy as np
import pandas as pd
import torch, torchvision
torch.__version__

'0.4.1'

## 1. Tensors
- Pytorch Tensors are similar to Tensors in TensorFlow. Both are based on NumPy arrays and function similar to how the NumPy array does.
- In a nutshell, Pytorch tensors are NumPy arrays with GPU computing.
- Note: from v.0.4.0, ```Variable``` is deprecated. Use only Tensors
- Documentation: [```torch.Tensor```](https://pytorch.org/docs/stable/tensors.html)

## 2. Creating tensors
Tensors can be created in a number of ways:

- From NumPy arrays
- From Python list/tuples
- Using Pytorch functions

In [8]:
# tensors can be created from arrays
# note that data type is conserved even though array is converted into tensor
x = np.array([1, 2, 3])
print(x)
print(x.dtype)
x = torch.from_numpy(x)
print(x)
print(x.dtype)

[1 2 3]
int64
tensor([1, 2, 3])
torch.int64


In [9]:
y = np.array([1., 2., 3.], dtype = np.float32)
print(y)
print(y.dtype)
y = torch.from_numpy(y)
print(y)
print(y.dtype)

[1. 2. 3.]
float32
tensor([1., 2., 3.])
torch.float32


In [13]:
# when creating tensor from list/tuple, data type can be designated explicitly
x = torch.tensor([1, 2, 3])
print(x)
print(x.dtype)

y = torch.IntTensor([1, 2, 3])
print(y)
print(y.dtype)

tensor([1, 2, 3])
torch.int64
tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [16]:
# there are some pytorch functions that are similar to those in numpy
x = torch.empty(5)           # 1d tensor, uninitialized
print(x)
x = torch.randn(4, 2)        # 2d random tensor
print(x)
x = torch.zeros(1, 2, 4)     # 3d tensor 
print(x)
x = torch.ones(1, 2, 4)      # 3d tensor 
print(x)

tensor([[0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000],
        [0.0000, 0.0000]])
tensor([ 1.1233,  2.0569,  0.6844, -1.1102, -0.4936])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


## 3. Tensor Data Types
- There are 8 data types in Pytorch and each has corresponding NumPy data type and CPU/GPU tensor instances
  - ```torch.uint8```
  - ```torch.float16``` (```torch.half```)
  - ```torch.float32``` (```torch.float```)
  - ```torch.float64``` (```torch.double```)
  - ```torch.int8``` 
  - ```torch.int16``` (```torch.short```)
  - ```torch.int32``` (```torch.int```)
  - ```torch.int64``` (```torch.long```)
- Each tensor has its own data type and it can be changed
- CPU tensor can be changed into GPU tensor and vice versa

In [27]:
# explicitly setting and printing out data type 
x = torch.zeros(3, 2, dtype = torch.double)
print(x.dtype)

torch.float64


In [0]:
# operation between tensors with different data types is not allowed
x = torch.zeros(2, 2, dtype = torch.int)
y = torch.zeros(2, 2, dtype = torch.float)
print(x + y)    # error

In [26]:
# changing data type of tensor
x = torch.FloatTensor([1, 2, 3])
print(x.dtype)
x = x.long()
print(x.dtype)

torch.float32
torch.int64


In [39]:
# creating a GPU tensor
device = torch.device("cuda")
x = torch.ones(3, device = device)
y = torch.ones(3)
print(x)
print(y)

tensor([1., 1., 1.], device='cuda:0')
tensor([1., 1., 1.])


In [36]:
# converting CPU tensor to GPU tensor
device = torch.device("cuda")
x = torch.FloatTensor([1, 2, 3])
print(x)
x = x.to(device)
print(x)

tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')


In [37]:
# converting GPU tensor to CPU tensor
print(x)
x = x.cpu()
print(x)

tensor([1., 2., 3.], device='cuda:0')
tensor([1., 2., 3.])


## 4. Size (shape) of Tensors
- Size of a tensor is equivalent to shape of NumPy array
  - Size of a tensor can be displayed using ```size()```
  - A tensor can be reshaped using ```view()```

In [42]:
# size of tensor is equivalent to shape of NumPy array
x = np.asarray([2, 4, 5])
print(x.shape)
x = torch.tensor([2, 4, 5])
print(x.size())

x = np.asarray([[1,2], [3,4]])
print(x.shape)
x = torch.tensor([[1,2], [3,4]])
print(x.size())

(3,)
torch.Size([3])
(2, 2)
torch.Size([2, 2])


In [43]:
# reshaping tensors
x = torch.ones(2, 8, dtype = torch.float)
print(x.size())
x = x.view(4, 4)
print(x.size())
x = x.view(8, -1)
print(x.size())

torch.Size([2, 8])
torch.Size([4, 4])
torch.Size([8, 2])


In [44]:
# to get scalar value of tensor with size 1, use item()
x = torch.tensor([7])
x /= 7
print(x)
print(x.item())

tensor([1])
1
